name: "commit to notion"
author: BatuhanÖzen
description: "Write your last commit to notion database."
inputs:
  SECRET_GITHUB:
    description: "GitHub token"
    required: true
  NOTION_API_KEY:
    description: "Notion API Key"
    required: true
  NOTION_DATABASE:
    description: "Notion Database ID"
    required: true
  OWNER:
    description: "Notion API Key"
    required: true
  REPO:
    description: "Notion Database ID"
    required: true

runs:
  using: node12
  main: index.js