# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      SECRET_GITHUB:
        require: true
        type: string
      NOTION_API_KEY:
        require: true
        type: string
      NOTION_DATABASE:
        require: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: export SECRET_GITHUB=${{inputs.SECRET_GITHUB}}
    - run: export NOTION_API_KEY=${{inputs.NOTION_API_KEY}}
    - run: export NOTION_DATABASE=${{inputs.NOTION_API_KEY}}
    - run: node index.js
